# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and lock file
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy entire repository
COPY . ./

# Build the project
RUN npm run build

# Expose port if necessary (optional)
# EXPOSE 3000

# Run the MCP server
CMD ["node", "build/index.js"]
